#!/bin/sh
### gitlint commit-msg hook start ###

# TODO (jorisroovers): Test in SourceTree

exec < /dev/tty

python -m gitlint.cli --staged run-hook --msg-filename "$1"
exit $?
# exit 0 # TODO: fix to be exit code of gitlint

### gitlint commit-msg hook end ###
